spring:
  datasource:
    url: jdbc:h2:mem:ksch
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  # TODO Apply live authorization server
  # TODO Move mock authorization server into dev profile
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://noauth-ga2speboxa-ew.a.run.app/token-info
          client-id: dev
          client-secret: dev

management:
  endpoints:
    web:
      cors:
        allowedOrigins: '*'
        allowedMethods: GET
      basePath: /api/actuator
  health:
    diskspace:
      enabled: false
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
