spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: test
#    password: test
#    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      cors:
        allowedOrigins: '*'
        allowedMethods: GET
      basePath: /api/actuator
  health:
    diskspace:
      enabled: false
