server:
  port: ${PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ksch-workflows.eu.auth0.com/
    filter-order: "5"

oauth:
  baseUrl: https://ksch-workflows.eu.auth0.com
