spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
    driverClassName: org.h2.Driver
#  jpa:
    # TODO Can this be removed?
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
