spring:
  datasource:
    url: "jdbc:postgresql:///postgres?cloudSqlInstance=*****:*****:*****&socketFactory=com.google.cloud.sql.postgres.SocketFactory"
    username: "*****"
    password: "*****"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      cors:
        allowedOrigins: '*'
        allowedMethods: GET
      basePath: /api/actuator
  health:
    diskspace:
      enabled: false
