spring:
  datasource:
    data: classpath:org/springframework/session/jdbc/schema-h2.sql

oauth:
  baseUrl: http://authorization-server
  clientId: example_client_id
  clientSecret: example_client_secret
  redirectUri: http://localhost/redirect
