openapi: 3.1.0
info:
  version: 0.1.0
  title: K.S.C.H. Workflows
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: |
    This website contains the HTTP endpoints that are offered by the [backend](https://github.com/ksch-workflows/backend) component for frontend components of the [K.S.C.H. Workflows](https://ksch-workflows.github.io/) project.
servers:
  - url: 'http://example.com/api'
tags:
  - name: Patient
    description: People coming into the hospital for treatment.
  - name: Visit
    description: Data about a patient from the time of the registration in the hospital to the time of the discharge.

paths:
  '/patients':
    post:
      operationId: createPatient
      tags:
        - Patient
      summary: Create a patient
      security:
        - main_auth:
            - 'write:patients'
      requestBody: 
        description: Object containing the patient details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
            examples:
              registeredPatient:
                summary: A patient that has been registered.
                value: 
                  name: "John Doe"
                  gender: MALE
                  patientCategory: "GENERAL"
                  phoneNumber: "01234567890"
                  residentialAddress: "Guesthouse"
              emergency:
                summary: In case of emergency a patient may be created with empty details.
                value: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientResponse'

    get:
      operationId: listAllPatients
      tags:
        - Patient
      summary: List all patients
      security:
        - main_auth:
            - 'read:patients'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientListResponse'       

  '/patients/search':
    post:
      operationId: searchPatients
      tags:
        - Patient
      summary: Search for patients
      security:
        - main_auth:
            - 'read:patients'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientListResponse'

  '/patients/{patientId}':
    get:
      operationId: getPatientById
      tags:
        - Patient
      summary: Get the details of an individual patient
      security:
        - main_auth:
            - 'read:patients'
      parameters:
        - name: patientId
          in: path
          description: The ID of the patient to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientResponse'
              example:
                _id: "b5ac2f19-56c3-4db9-9d6d-76a821cff842"
                name: "John Doe"
                gender: "MALE"
                patientCategory: "GENERAL"
                phoneNumber: "01234567890"
                residentialAddress: "Guesthouse"          

  '/patients/{patientId}/visits':
    post:
      operationId: createVisit
      summary: Create a visit for a patient
      security: 
        -  main_auth:
            - 'write:visits'
      parameters: 
        - name: patientId
          in: path
          description: The ID of the affected patient
          required: true
          schema:
            type: string
            format: uuid
      requestBody: 
        description: Object containing the visit details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VisitRequest"
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VisitResponse"        

  '/patients/{patientId}/visits/{visitId}':
    get:
      operationId: getVisitById
      summary: Get the details of an individual visit
      security: 
        -  main_auth:
            - 'read:visits'
      parameters:
        - name: patientId
          in: path
          description: The ID of the affected patient
          required: true
          schema:
            type: string
            format: uuid
        - name: visitId
          in: path
          description: The ID of the visit to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitResponse'

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://example.com/api/authorize
          tokenUrl: https://ksch-workflows.eu.auth0.com/oauth/token
          scopes: {}
  schemas:
    VisitType:
      type: string
      enum:
        - OPD
        - IPD
        - PHYSIOTHERAPY
        - EMERGENCY
    VisitRequest:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/VisitType"
    VisitResponse:
      allOf:
      - type: object
        required:
        - _id
        - type
        - opdNumber
        - timeStart
        properties:
          _id:
            description: Technical identifier of the visit
            type: string
            format: uuid
            example: ce1d3f10-eef8-4f3e-a598-928e6d6fcdb9
      - $ref: '#/components/schemas/VisitRequest'
      - type: object
        properties:
          opdNumber:
            description: OPD number of the visit
            type: string
            example: "21-1001"
          timeStart:
            type: string
            format: date-time
            description: The time of the patient registration
          timeEnd:
            type: string
            format: date-time
            description: The time of the patient discharge
            example: "2019-08-27T08:07:22Z"    
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
        - OTHER
    PatientCategory:
      type: string
      enum:
        - GENERAL
        - INPATIENT
        - OUTPATIENT
    Patient:
      type: object
      properties:
        name:
          description: All the name parts, i.e. first name, middle name, and last name.
          type: string
          minLength: 1
          example: John Doe
        gender:
          $ref: '#/components/schemas/Gender'
        patientCategory:
          $ref: '#/components/schemas/PatientCategory'
        phoneNumber:
          description: Patient phone number
          type: string
          minLength: 1
          example: "+1234567890"
        residentialAddress:
          description: Patient residential address
          type: string
          minLength: 1
          example: 1234 Main St, City, State 12345
    PatientResponse:
      allOf:
      - type: object
        required:
        - _id
        properties:
          _id:
            description: Technical identifier of the patient
            type: string
            format: uuid
      - $ref: '#/components/schemas/Patient'
    Page:
      type: object
      properties: 
        size:
          type: integer
          description: The number of elements in the page
          example: 20
        totalElements:
          type: integer
          description: The total number of elements
          example: 1
        totalPages:
          type: integer
          description: The total number of pages
          example: 1
        number:
          type: integer
          description: The page number
          example: 0
    PatientListResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            patientResourceList:
              type: array
              items:
                $ref: '#/components/schemas/PatientResponse'
        page:
          $ref: "#/components/schemas/Page"
